name: my_cool_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  getwidget: ^3.0.1
  flutter:
    sdk: flutter
  fl_chart: ^0.55.2
  touchable: ^1.0.2
  line_chart: ^1.1.11
  oktoast: ^3.3.1
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

